eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

---
spring:
  profiles: prod
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
